In [165]:
""" Imports and Path Setup """
%load_ext autoreload
%autoreload 2

import sys
import os

root = os.path.abspath("..")
if root not in sys.path:
    sys.path.insert(0, root)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [166]:
import pandas as pd
from src.data_loader import load_raw_data, get_data_shape_summary

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [169]:
"""Load raw Data"""
RAW_PATH="E:\\BongoDev-AI-Professional_Bootcamp\\telecom-churn-analysis\\data\\raw\\telecom_customers.csv"
df_raw=load_raw_data(RAW_PATH)
df_raw.head()
df_raw.tail()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract_type,paperless_billing,payment_method,monthly_charges,total_charges,churn
4996,CUST-04996,Male,0,Yes,No,1,Yes,Yes,DSL,No,No,No,No,Yes,No,Two year,No,NaN,64.95,70.65,No
4997,CUST-04997,F,0,Yes,No,66,Yes,Yes,Fiber optic,No,No,No,No,Yes,Yes,Month-to-month,Yes,Mailed check,92.65,6109.88,Yes
4998,CUST-04998,Male,1,Yes,Yes,47,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Electronic check,31.21,1465.45,No
4999,CUST-04999,Female,0,No,No,68,Yes,No,Fiber optic,Yes,Yes,Yes,No,No,No,Two year,No,Credit card,97.14,6607.0,No
5000,CUST-05000,Female,0,Yes,Yes,27,Yes,Yes,DSL,Yes,No,No,No,No,Yes,One year,No,Electronic check,72.48,1958.25,No

In [171]:
df=df_raw.copy()

In [172]:
"""Run Profiler"""
get_data_shape_summary(df)

{'n_rows': 5001, 'n_columns': 21, 'n_cells': 105021}

In [173]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5001 non-null   str
 1   gender             5001 non-null   str
 2   senior_citizen     5001 non-null   int64
 3   partner            5001 non-null   str
 4   dependents         4801 non-null   str
 5   tenure_months      5001 non-null   int64
 6   phone_service      5001 non-null   str
 7   multiple_lines     5001 non-null   str
 8   internet_service   5001 non-null   str
 9   online_security    5001 non-null   str
 10  online_backup      5001 non-null   str
 11  device_protection  5001 non-null   str
 12  tech_support       5001 non-null   str
 13  streaming_tv       5001 non-null   str
 14  streaming_movies   5001 non-null   str
 15  contract_type      5001 non-null   str
 16  paperless_billing  5001 non-null   str
 17  payment_method     4851 non-null   str
 18  monthly_charges    5001 non-null   float64
 19  total_charges      5001 non-null   str
 20  churn              5001 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.3 MB

In [155]:
for col in df.columns:
    print(f"Column: {col}")

Column: customer_id
Column: gender
Column: senior_citizen
Column: partner
Column: dependents
Column: tenure_months
Column: phone_service
Column: multiple_lines
Column: internet_service
Column: online_security
Column: online_backup
Column: device_protection
Column: tech_support
Column: streaming_tv
Column: streaming_movies
Column: contract_type
Column: paperless_billing
Column: payment_method
Column: monthly_charges
Column: total_charges
Column: churn

In [156]:
df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure_months', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract_type',
       'paperless_billing', 'payment_method', 'monthly_charges',
       'total_charges', 'churn'],
      dtype='str')

In [157]:
df['tenure_months'].dtype

dtype('int64')

In [174]:
for col in df. columns:
    # print(f"Column: {col}, Type: {df[col].dtype}")
    print(f"{col},Type:{df[col].dtype}")

customer_id,Type:str
gender,Type:str
senior_citizen,Type:int64
partner,Type:str
dependents,Type:str
tenure_months,Type:int64
phone_service,Type:str
multiple_lines,Type:str
internet_service,Type:str
online_security,Type:str
online_backup,Type:str
device_protection,Type:str
tech_support,Type:str
streaming_tv,Type:str
streaming_movies,Type:str
contract_type,Type:str
paperless_billing,Type:str
payment_method,Type:str
monthly_charges,Type:float64
total_charges,Type:str
churn,Type:str

In [175]:
record=[]
for col in df.columns:
    n_unique=df[col].nunique(dropna=True)
    # print(f"{col}: {n_unique}")
    sample=df[col].dropna().iloc[0] if df[col].notna().any else None
    # print(f"Sample value: {sample}")
    stored_type=str(df[col].dtype)

    is_suspicios= False
    if df[col].dtype=='object':
        converted=pd.to_numeric(df[col], errors='coerce')
        pct_covertible=converted.notna().mean()
        if pct_covertible>0.9:
            is_suspicios=True
    # print(f"Is suspicious: {is_suspicios}")
    record.append({
        "column": col,
        "stored_type":stored_type,
        "n_unique": n_unique,
        "sample_value": sample, 
        "dtype_suspicious": is_suspicios})
print(pd.DataFrame(record))

               column stored_type  n_unique         sample_value  \
0         customer_id         str      5000           CUST-00005
1              gender         str         5                 Male
2      senior_citizen       int64         2                    0
3             partner         str         2                  Yes
4          dependents         str         2                  Yes
5       tenure_months       int64        74                   53
6       phone_service         str         2                  Yes
7      multiple_lines         str         3                   No
8    internet_service         str         3                   No
9     online_security         str         3  No internet service
10      online_backup         str         3  No internet service
11  device_protection         str         3  No internet service
12       tech_support         str         3  No internet service
13       streaming_tv         str         3  No internet service
14   streaming_movies         str         3  No internet service
15      contract_type         str         4             Two year
16  paperless_billing         str         2                  Yes
17     payment_method         str         4     Electronic check
18    monthly_charges     float64      3414                29.29
19      total_charges         str      4913              1553.16
20              churn         str         2                   No

    dtype_suspicious
0              False
1              False
2              False
3              False
4              False
5              False
6              False
7              False
8              False
9              False
10             False
11             False
12             False
13             False
14             False
15             False
16             False
17             False
18             False
19             False
20             False

In [176]:
from src.profiler import audit_dtypes,missing_value_report,duplicate_report

audit_dtypes(df)

,column,stored_dtype,n_unique,sample_value,dtype_suspicious
0,customer_id,str,5000,CUST-00005,False
1,gender,str,5,Male,False
2,senior_citizen,int64,2,0,False
3,partner,str,2,Yes,False
4,dependents,str,2,Yes,False
5,tenure_months,int64,74,53,False
6,phone_service,str,2,Yes,False
7,multiple_lines,str,3,No,False
8,internet_service,str,3,No,False
9,online_security,str,3,No internet service,False
10,online_backup,str,3,No internet service,False
11,device_protection,str,3,No internet service,False
12,tech_support,str,3,No internet service,False
13,streaming_tv,str,3,No internet service,False
14,streaming_movies,str,3,No internet service,False
15,contract_type,str,4,Two year,False
16,paperless_billing,str,2,Yes,False
17,payment_method,str,4,Electronic check,False
18,monthly_charges,float64,3414,29.29,False
19,total_charges,str,4913,1553.16,False
20,churn,str,2,No,False

In [177]:
missing_value_report(df)

,column,nan_count,blank_string_count,combined_missing,missing_pct
0,dependents,200,0,200,4.00
1,payment_method,150,0,150,3.00
2,customer_id,0,0,0,0.00
3,senior_citizen,0,0,0,0.00
4,gender,0,0,0,0.00
5,partner,0,0,0,0.00
6,tenure_months,0,0,0,0.00
7,multiple_lines,0,0,0,0.00
8,phone_service,0,0,0,0.00
9,online_security,0,0,0,0.00
10,online_backup,0,0,0,0.00
11,device_protection,0,0,0,0.00
12,internet_service,0,0,0,0.00
13,tech_support,0,0,0,0.00
14,streaming_tv,0,0,0,0.00
15,contract_type,0,0,0,0.00
16,streaming_movies,0,0,0,0.00
17,paperless_billing,0,0,0,0.00
18,monthly_charges,0,0,0,0.00
19,total_charges,0,0,0,0.00
20,churn,0,0,0,0.00

In [179]:
duplicate_report(df)

{'full_row_duplicates': 1,
 'id_duplicates': 1,
 'id_column': 'customer_id',
 'id_duplicate_examples':   customer_id gender  senior_citizen partner dependents  tenure_months  \
 0  CUST-00005   Male               0     Yes        Yes             53
 5  CUST-00005   Male               0     Yes        Yes             53

   phone_service multiple_lines internet_service      online_security  \
 0           Yes             No               No  No internet service
 5           Yes             No               No  No internet service

          online_backup    device_protection         tech_support  \
 0  No internet service  No internet service  No internet service
 5  No internet service  No internet service  No internet service

           streaming_tv     streaming_movies contract_type paperless_billing  \
 0  No internet service  No internet service      Two year               Yes
 5  No internet service  No internet service      Two year               Yes

      payment_method  monthly_charges total_charges churn
 0  Electronic check            29.29       1553.16    No
 5  Electronic check            29.29       1553.16    No  }

In [180]:
from src.profiler import run_full_profile
report= run_full_profile(df, id_column="customer_id")
report

{'shape': {'n_rows': 5001, 'n_columns': 21},
 'dtype_audit':                column stored_dtype  n_unique         sample_value  \
 0         customer_id          str      5000           CUST-00005
 1              gender          str         5                 Male
 2      senior_citizen        int64         2                    0
 3             partner          str         2                  Yes
 4          dependents          str         2                  Yes
 5       tenure_months        int64        74                   53
 6       phone_service          str         2                  Yes
 7      multiple_lines          str         3                   No
 8    internet_service          str         3                   No
 9     online_security          str         3  No internet service
 10      online_backup          str         3  No internet service
 11  device_protection          str         3  No internet service
 12       tech_support          str         3  No internet service
 13       streaming_tv          str         3  No internet service
 14   streaming_movies          str         3  No internet service
 15      contract_type          str         4             Two year
 16  paperless_billing          str         2                  Yes
 17     payment_method          str         4     Electronic check
 18    monthly_charges      float64      3414                29.29
 19      total_charges          str      4913              1553.16
 20              churn          str         2                   No

     dtype_suspicious
 0              False
 1              False
 2              False
 3              False
 4              False
 5              False
 6              False
 7              False
 8              False
 9              False
 10             False
 11             False
 12             False
 13             False
 14             False
 15             False
 16             False
 17             False
 18             False
 19             False
 20             False  ,
 'missing_report':                column  nan_count  blank_string_count  combined_missing  \
 0          dependents        200                   0               200
 1      payment_method        150                   0               150
 2         customer_id          0                   0                 0
 3      senior_citizen          0                   0                 0
 4              gender          0                   0                 0
 5             partner          0                   0                 0
 6       tenure_months          0                   0                 0
 7      multiple_lines          0                   0                 0
 8       phone_service          0                   0                 0
 9     online_security          0                   0                 0
 10      online_backup          0                   0                 0
 11  device_protection          0                   0                 0
 12   internet_service          0                   0                 0
 13       tech_support          0                   0                 0
 14       streaming_tv          0                   0                 0
 15      contract_type          0                   0                 0
 16   streaming_movies          0                   0                 0
 17  paperless_billing          0                   0                 0
 18    monthly_charges          0                   0                 0
 19      total_charges          0                   0                 0
 20              churn          0                   0                 0

     missing_pct
 0          4.00
 1          3.00
 2          0.00
 3          0.00
 4          0.00
 5          0.00
 6          0.00
 7          0.00
 8          0.00
 9          0.00
 10         0.00
 11         0.00
 12         0.00
 13         0.00
 14         0.00
 15         0.00
 16         0.00
 17         0.00
 18         0.00
 19         0.00
 20         0.00  ,
 'duplicate_report': {'full_row_duplicates': 1,
  'id_duplicates': 1,
  'id_column': 'customer_id',
  'id_duplicate_examples':   customer_id gender  senior_citizen partner dependents  tenure_months  \
  0  CUST-00005   Male               0     Yes        Yes             53
  5  CUST-00005   Male               0     Yes        Yes             53

    phone_service multiple_lines internet_service      online_security  \
  0           Yes             No               No  No internet service
  5           Yes             No               No  No internet service

           online_backup    device_protection         tech_support  \
  0  No internet service  No internet service  No internet service
  5  No internet service  No internet service  No internet service

            streaming_tv     streaming_movies contract_type paperless_billing  \
  0  No internet service  No internet service      Two year               Yes
  5  No internet service  No internet service      Two year               Yes

       payment_method  monthly_charges total_charges churn
  0  Electronic check            29.29       1553.16    No
  5  Electronic check            29.29       1553.16    No  },
 'cardinality_report':                column  n_unique  pct_unique                inferred_type
 0         customer_id      5000       99.98             high-cardinality
 1       total_charges      4913       98.24             high-cardinality
 2     monthly_charges      3414       68.27             high-cardinality
 3       tenure_months        74        1.48             high-cardinality
 4              gender         5        0.10  low-cardinality categorical
 5      payment_method         4        0.08  low-cardinality categorical
 6       contract_type         4        0.08  low-cardinality categorical
 7       online_backup         3        0.06  low-cardinality categorical
 8        tech_support         3        0.06  low-cardinality categorical
 9        streaming_tv         3        0.06  low-cardinality categorical
 10     multiple_lines         3        0.06  low-cardinality categorical
 11   internet_service         3        0.06  low-cardinality categorical
 12    online_security         3        0.06  low-cardinality categorical
 13   streaming_movies         3        0.06  low-cardinality categorical
 14  device_protection         3        0.06  low-cardinality categorical
 15     senior_citizen         2        0.04                       binary
 16            partner         2        0.04                       binary
 17         dependents         2        0.04                       binary
 18      phone_service         2        0.04                       binary
 19  paperless_billing         2        0.04                       binary
 20              churn         2        0.04                       binary,
 'target_distribution':   class  count  percentage     imbalance_flag
 0    No   3813       76.24
 1   Yes   1188       23.76  ⚠  minority class}

In [182]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5001 non-null   str
 1   gender             5001 non-null   str
 2   senior_citizen     5001 non-null   int64
 3   partner            5001 non-null   str
 4   dependents         4801 non-null   str
 5   tenure_months      5001 non-null   int64
 6   phone_service      5001 non-null   str
 7   multiple_lines     5001 non-null   str
 8   internet_service   5001 non-null   str
 9   online_security    5001 non-null   str
 10  online_backup      5001 non-null   str
 11  device_protection  5001 non-null   str
 12  tech_support       5001 non-null   str
 13  streaming_tv       5001 non-null   str
 14  streaming_movies   5001 non-null   str
 15  contract_type      5001 non-null   str
 16  paperless_billing  5001 non-null   str
 17  payment_method     4851 non-null   str
 18  monthly_charges    5001 non-null   float64
 19  total_charges      5001 non-null   str
 20  churn              5001 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.3 MB